// Auto-generated by scripts/generate-collision-masks.py
// 32x32 bitmask. Each Uint32 = one row, bit N = column N.
export const MASK_SIZE = 32;

// prettier-ignore
export const BEAVER_MASK = new Uint32Array([
  0x00000000,
  0x00000000,
  0x00000000,
  0x00000000,
  0x00480000,
  0x00FFC000,
  0x00FF8000,
  0x00FFC000,
  0x01FFDE00,
  0x01FFFF00,
  0x01FFFF80,
  0x01FFFF80,
  0x01FFFFC0,
  0x01FFFFC0,
  0x01FFFFC0,
  0x01FFFFC0,
  0x03FFFFC0,
  0x03FFFFC0,
  0x03FFFF80,
  0x03FFFF80,
  0x03FFFF00,
  0x03FFFE00,
  0x01FFFC00,
  0x01FFE000,
  0x00FFC000,
  0x00878000,
  0x00000000,
  0x00000000,
  0x00000000,
  0x00000000,
  0x00000000,
  0x00000000,
]);
