#!/usr/bin/env python3
"""
Generate 32x32 Uint32Array collision masks for the beaver sprite and all obstacle photos.

Scans all 4 beaver animation frames, unions their opaque pixels (alpha > 30),
and produces a 32-entry Uint32Array (one uint32 per row, bit N = column N).
Does the same for each obstacle photo in the obstacles directory.

Outputs:
  web/lib/beaverCollisionMask.ts
  web/lib/obstacleCollisionMasks.ts

Requirements: Pillow (`pip install Pillow`)

Usage:
    python3 scripts/generate-collision-masks.py
"""

from PIL import Image
import os
import glob

GRID = 32
ALPHA_THRESHOLD = 30
SAMPLE_STEP = 4

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.join(SCRIPT_DIR, '..')
ASSETS_DIR = os.path.join(PROJECT_DIR, 'web', 'public', 'teamGame-assets')
LIB_DIR = os.path.join(PROJECT_DIR, 'web', 'lib')

BEAVER_FRAMES = [
    'beaver-walk1.png',
    'beaver-walk2.png',
    'beaver-jump1.png',
    'beaver-jump2.png',
]


def image_to_mask(img: Image.Image) -> list[int]:
    """Convert an RGBA image to a 32-entry list of uint32 row masks."""
    w, h = img.size
    pixels = img.load()
    rows = []

    for row in range(GRID):
        py0 = int(row / GRID * h)
        py1 = min(h - 1, int((row + 1) / GRID * h))
        row_bits = 0

        for col in range(GRID):
            px0 = int(col / GRID * w)
            px1 = min(w - 1, int((col + 1) / GRID * w))

            found = False
            for py in range(py0, py1 + 1, SAMPLE_STEP):
                for px in range(px0, px1 + 1, SAMPLE_STEP):
                    if pixels[px, py][3] > ALPHA_THRESHOLD:
                        found = True
                        break
                if found:
                    break

            if found:
                row_bits |= (1 << col)

        rows.append(row_bits)

    return rows


def beaver_mask_union() -> list[int]:
    """Union all beaver frames into a single 32x32 mask, accounting for object-contain."""
    frames = [Image.open(os.path.join(ASSETS_DIR, f)).convert('RGBA') for f in BEAVER_FRAMES]
    w, h = frames[0].size
    aspect = w / h

    # object-contain in a square container
    img_x_start = (1.0 - aspect) / 2
    img_x_end = 1.0 - img_x_start

    all_pixels = [f.load() for f in frames]
    rows = []

    for row in range(GRID):
        row_bits = 0
        for col in range(GRID):
            cx0 = col / GRID
            cx1 = (col + 1) / GRID

            if cx1 <= img_x_start or cx0 >= img_x_end:
                continue

            cy0 = row / GRID
            cy1 = (row + 1) / GRID

            cx0 = max(cx0, img_x_start)
            cx1 = min(cx1, img_x_end)

            img_fx0 = (cx0 - img_x_start) / aspect
            img_fx1 = (cx1 - img_x_start) / aspect
            px_x0 = int(img_fx0 * w)
            px_x1 = min(w - 1, int(img_fx1 * w))
            px_y0 = int(cy0 * h)
            px_y1 = min(h - 1, int(cy1 * h))

            found = False
            for pixels in all_pixels:
                for py in range(px_y0, px_y1 + 1, SAMPLE_STEP):
                    for px in range(px_x0, px_x1 + 1, SAMPLE_STEP):
                        if pixels[px, py][3] > ALPHA_THRESHOLD:
                            found = True
                            break
                    if found:
                        break
                if found:
                    break

            if found:
                row_bits |= (1 << col)

        rows.append(row_bits)

    return rows


def format_uint32_array(rows: list[int]) -> str:
    """Format a list of uint32 values as a TypeScript Uint32Array literal."""
    lines = []
    for val in rows:
        lines.append(f'  0x{val:08X},')
    return 'new Uint32Array([\n' + '\n'.join(lines) + '\n])'


def main():
    os.makedirs(LIB_DIR, exist_ok=True)

    # Beaver mask
    print('Generating beaver mask...')
    beaver_rows = beaver_mask_union()
    solid = sum(bin(r).count('1') for r in beaver_rows)
    print(f'  Beaver solid cells: {solid}/{GRID * GRID}')

    beaver_ts = (
        '// Auto-generated by scripts/generate-collision-masks.py\n'
        '// 32x32 bitmask. Each Uint32 = one row, bit N = column N.\n'
        f'export const MASK_SIZE = {GRID};\n'
        '\n'
        '// prettier-ignore\n'
        f'export const BEAVER_MASK = {format_uint32_array(beaver_rows)};\n'
    )

    with open(os.path.join(LIB_DIR, 'beaverCollisionMask.ts'), 'w') as f:
        f.write(beaver_ts)
    print('  Wrote web/lib/beaverCollisionMask.ts')

    # Obstacle masks
    print('Generating obstacle masks...')
    obstacles_dir = os.path.join(ASSETS_DIR, 'teamGame-photos', 'obstacles')
    obstacle_files = sorted(glob.glob(os.path.join(obstacles_dir, '*-r.png')))

    masks = {}
    for filepath in obstacle_files:
        name = os.path.basename(filepath)
        img = Image.open(filepath).convert('RGBA')
        rows = image_to_mask(img)
        key = f'/teamGame-assets/teamGame-photos/obstacles/{name}'
        masks[key] = rows
        solid = sum(bin(r).count('1') for r in rows)
        print(f'  {name}: {solid}/{GRID * GRID} solid')

    entries = []
    for key, rows in masks.items():
        entries.append(f"  '{key}': {format_uint32_array(rows)},")

    obs_ts = (
        '// Auto-generated by scripts/generate-collision-masks.py\n'
        '// 32x32 bitmask per obstacle photo. Each Uint32 = one row, bit N = column N.\n'
        f'export const OBS_MASK_SIZE = {GRID};\n'
        '\n'
        '// prettier-ignore\n'
        'const MASKS: Record<string, Uint32Array> = {\n'
        + '\n'.join(entries) +
        '\n};\n'
        '\n'
        'export function getObstacleMask(photo: string): Uint32Array | undefined {\n'
        '  return MASKS[photo];\n'
        '}\n'
    )

    with open(os.path.join(LIB_DIR, 'obstacleCollisionMasks.ts'), 'w') as f:
        f.write(obs_ts)
    print(f'  Wrote web/lib/obstacleCollisionMasks.ts ({len(masks)} obstacles)')


if __name__ == '__main__':
    main()
